"""Add category to Expense

Revision ID: b398a140be5d
Revises: bd0fa19b8431
Create Date: 2025-07-02 01:07:49.923934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b398a140be5d'
down_revision = 'bd0fa19b8431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        ##batch_op.add_column(sa.Column('category', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('category', sa.String(), nullable=False, server_default='Other'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
